Use stable hash as unique identifier for types, instead of unstable human-readable names
model-checking/rmc pull request #496
Opened 2021-09-17 20:46 UTC by danielsn

### Description of changes: 

Describe RMC's current behavior and how your code changes that behavior. If there are no issues this PR is resolving, explain why this change is necessary.

### Resolved issues:

Resolves #ISSUE-NUMBER

### Call-outs:

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

2021-09-17 22:40 UTC, celinval requested changes

2021-09-17 22:40 UTC, celinval commented on compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/utils.rs
>      pub fn is_rust_unique_pointer(&self) -> bool {
Ditto

2021-09-17 22:40 UTC, celinval commented on compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/utils.rs
> +        true
Can we just remove this function?

2021-09-23 01:24 UTC, danielsn commented on compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/utils.rs
> +        true
Fixed in previous PR

2021-09-23 01:24 UTC, danielsn commented on compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/utils.rs
>      pub fn is_rust_unique_pointer(&self) -> bool {
Fixed in previous PR

2021-09-23 17:59 UTC, tedinski approved these changes

2021-09-23 18:18 UTC, avanhatt approved these changes
LGTM with a few documentation suggestions

2021-09-23 18:18 UTC, avanhatt commented on compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/symbol.rs
> +        Symbol::new(name, Location::none(), t, SymbolValues::None, Some(base_name), pretty_name)
Maybe a comment here to indicate this is not yet used in `--gen-c`?

2021-09-23 18:18 UTC, avanhatt commented on src/test/rmc-multicrate/type-mismatch/run-mismatch-test.sh
> +  echo "Successful dependency test"
Maybe include "mismatch" in message?

2021-09-23 18:47 UTC, merged