Structural check for Rust types instead of name based
model-checking/rmc pull request #499
Opened 2021-09-20 20:47 UTC by danielsn

### Description of changes: 

Describe RMC's current behavior and how your code changes that behavior. If there are no issues this PR is resolving, explain why this change is necessary.

### Resolved issues:

Resolves #ISSUE-NUMBER

### Call-outs:

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

2021-09-20 22:31 UTC, avanhatt requested changes

2021-09-20 22:31 UTC, avanhatt commented on compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/utils.rs
> +        // Is there something smarter we can do here?
File an issue for the "smarter" task?

2021-09-20 22:31 UTC, avanhatt commented on compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/utils.rs
> +    pub fn is_rust_phantom_data(&self, st: &SymbolTable) -> bool {
Maybe these should be `is_like_rust_phantom_data` to reflect false positives?

2021-09-21 18:31 UTC, celinval approved these changes

2021-09-22 16:42 UTC, merged