Handle non returning intrinsics
model-checking/rmc pull request #736
Opened 2022-01-07 22:27 UTC by adpaco-aws

### Description of changes: 

Adds a specific function for handling of non returning intrinsics, which currently are `abort` and a special case of `transmute`.

### Resolved issues:

Resolves #734 

### Call-outs:

Wrote a function for these special intrinsics but they can also be handled within the `codegen_intrinsic` function. That would require passing `p` as an option (i.e., not unwrap before call to `codegen_intrinsic`) and match on it at the beginning of `codegen_intrinsic`.

### Testing:

* How is this change tested? Existing regression + new test for transmute.

* Is this a refactor change? No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

2022-01-07 22:52 UTC, celinval commented on src/rmc-compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs
> +            "abort" => Stmt::assert_false("reached intrinsic::abort", loc),
I recommend using `GotocCtx::codegen_fatal_error()` here. The `Stmt::assert_false` will not abort the program execution path.

2022-01-07 22:53 UTC, celinval commented on src/rmc-compiler/rustc_codegen_rmc/src/codegen/intrinsic.rs
> +    pub fn codegen_nonret_intrinsic(
nit: I would rename it to `codegen_never_return_intrinsic()`

2022-01-07 23:01 UTC, celinval requested changes
It looks good. We do need to add either an `assume(false)` or `abort()` call after the `assert(false)` though. In gotoc, an assertion failure does not interrupt the execution flow which may cause some odd behavior.

2022-01-10 14:51 UTC, adpaco-aws commented
Thanks @celinval ! Renamed and replaced `assert(false)` by `codegen_fatal_error()` in both cases, since they have similar behaviors.

2022-01-10 17:39 UTC, celinval approved these changes
Perfect! Thanks

2022-01-11 14:11 UTC, merged